INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Wayne','vitae@Cumsociis.edu','9115','surname','Korea, North','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Alexander','sit.amet.risus@consequatauctornunc.net','2766','surname','Holy See (Vatican City State)','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Calista','Cras.sed.leo@nequeNullamut.org','4608','surname','Denmark','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Ezra','semper@vitaevelit.ca','6123','surname','Morocco','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Meghan','tempor@egestasblandit.edu','6984','surname','Guam','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Adara','sagittis.Duis@magna.net','8271','surname','British Indian Ocean Territory','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Kirsten','velit.dui@arcuAliquamultrices.com','6016','surname','Saint Lucia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Octavia','at.pede.Cras@euismod.org','2300','surname','Falkland Islands','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Eliana','vel@iaculisodioNam.co.uk','4095','surname','El Salvador','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Petra','non.dui.nec@magna.edu','3355','surname','Senegal','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Alice','mollis.nec@tinciduntnuncac.co.uk','2161','surname','Djibouti','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Heather','eget.mollis.lectus@justoProin.com','3785','surname','Sweden','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Keaton','magna.sed@vulputateeu.ca','8955','surname','Brunei','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Conan','Etiam@adipiscing.com','7062','surname','Rwanda','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Hamish','condimentum@vellectusCum.org','1141','surname','Somalia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Kareem','non@egestasnunc.net','2616','surname','Sudan','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Casey','fermentum.risus@interdumSedauctor.edu','2419','surname','Virgin Islands, United States','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Quynn','Duis.dignissim@arcuet.co.uk','7308','surname','Croatia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Paki','Mauris@non.edu','5230','surname','Croatia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Alexandra','mauris@semmollisdui.com','4265','surname','Niger','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Winter','urna.Ut@lorem.edu','6940','surname','Malaysia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Leah','aliquet.sem@lobortistellusjusto.org','9356','surname','Solomon Islands','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Quin','tincidunt@vehicula.edu','9293','surname','Libya','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Shelby','fermentum@scelerisqueneque.org','4882','surname','Montserrat','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Lacey','in.dolor.Fusce@nuncrisusvarius.edu','9653','surname','Macedonia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Shellie','Nullam@vitaealiquam.ca','2823','surname','Nicaragua','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Piper','libero.et@vehiculaPellentesquetincidunt.edu','9453','surname','Burkina Faso','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Juliet','mauris.aliquam@lacusvestibulum.com','8279','surname','Macao','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Kyla','elit@In.com','4640','surname','Malaysia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Clare','nec@Nulla.edu','5369','surname','Liechtenstein','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Penelope','mi.pede.nonummy@turpis.net','5286','surname','Singapore','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Kim','est.arcu@disparturient.ca','8666','surname','United States','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Cole','sodales.at.velit@Quisquenonummyipsum.org','9052','surname','Hong Kong','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Aretha','eget@velit.ca','6738','surname','Albania','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Hedley','ac.orci.Ut@nibhDonecest.edu','5581','surname','Saint Barthélemy','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Sarah','metus.sit@arcuet.ca','9201','surname','Samoa','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Whoopi','commodo.at.libero@vulputate.co.uk','9907','surname','Falkland Islands','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Amethyst','non@felis.org','9787','surname','El Salvador','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Scarlet','convallis.in.cursus@utcursusluctus.org','5717','surname','Lithuania','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Jack','nibh.Quisque@vulputate.co.uk','8495','surname','Sudan','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Alice','nec.enim@consequatlectus.net','3689','surname','Oman','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Jolene','Mauris.quis@faucibus.net','2261','surname','Israel','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Wade','velit.dui.semper@posuerecubiliaCurae.org','4616','surname','Georgia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Baxter','Phasellus.elit@CrasinterdumNunc.com','8568','surname','Mongolia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Harper','pellentesque.tellus.sem@sollicitudincommodo.ca','1923','surname','Bouvet Island','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Stewart','faucibus.ut.nulla@bibendumDonec.net','9774','surname','Armenia','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Whoopi','dignissim@ametultriciessem.net','9389','surname','Ghana','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Shelby','ultrices@enimnislelementum.org','3520','surname','Bosnia and Herzegovina','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Ima','Suspendisse@ullamcorpernisl.com','5102','surname','Mauritius','Publisher');
INSERT INTO users (name,email,password,photoUrl,country,permission) VALUES ('Jenette','sed.pede@loremfringilla.com','5343','surname','Guatemala','Publisher');


INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Maecenas vulputate luctus nec justo magna, rhoncus a purus quisque justo, vel earum vitae placerat, facilisi nullam.','Porttitor Vulputate Posuere PC','04/05/17','dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris','Sports','Visible',15);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Vulputate Nisi Ltd','04/05/17','urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna,','Sports','Visible',25);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Curabitur sed tortor. Integer aliquam adipiscing lacus.','In PC','04/05/17','dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna','Sports','Visible',46);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Duis a mi fringilla mi lacinia mattis. Integer eu lacus.','Dolor Quam Consulting','04/05/17','vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo','Sports','Visible',12);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Etiam bibendum fermentum metus, aenean sed pede nec ante blandit viverra.','Augue Corp.','04/05/17','neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero','Sports','Visible',28);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Vivamus nisi. Mauris nulla, integer urna.','Aliquam Fringilla PC','04/05/17','ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed','Sports','Visible',14);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Fusce fermentum fermentum arcu, vestibulum ante ipsum primis.','Natoque Penatibus Consulting','04/05/17','non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci','Sports','Visible',31);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Phasellus at augue id ante dictum cursus.','Aenean Eget Magna Corporation','04/05/17','est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis','World','Visible',17);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Nulla tempor augue ac ipsum, phasellus vitae mauris sit amet lorem semper auctor.','Quisque Ac Corp.','04/05/17','dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis','World','Visible',4);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Pellentesque ultricies dignissim lacus, aliquam rutrum lorem ac risus.','Placerat Velit Corporation','04/05/17','vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed','World','Visible',5);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.','Mollis Vitae LLP','04/05/17','Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.','Technology','Hidden',30);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Suspendisse tristique neque venenatis lacus.','Fermentum Convallis Corp.','04/05/17','eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris','Technology','Visible',12);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Aenean egestas hendrerit neque, n ornare sagittis felis.','Elementum At LLC','04/05/17','aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes,','Technology','Visible',44);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Mauris blandit enim consequat purus, maecenas libero est, congue a.','Aptent Company','04/05/17','eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi','Technology','Visible',40);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Nunc sed orci lobortis augue scelerisque mollis, phasellus libero mauris.','Semper Auctor Mauris Associates','04/05/17','Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a,','Technology','Hidden',13);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Quisque ac libero nec ligula consectetuer rhoncus, nullam velit dui.','Senectus Et Limited','04/05/17','arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis,','Technology','Hidden',39);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Proin sed turpis nec mauris blandit mattis.','Ipsum Incorporated','04/05/17','nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent','Technology','Visible',30);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Pellentesque tincidunt tempus risus, donec egestas.','Dui Industries','04/05/17','vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper','Technology','Visible',42);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Tellus sem mollis dui, in sodales elit erat vitae risus.','Aliquam Vulputate Corp.','04/05/17','tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis','Technology','Visible',8);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Phasellus in felis, nulla tempor augue ac ipsum, phasellus vitae mauris sit amet.','Lacus Mauris LLC','04/05/17','Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam','Technology','Visible',11);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est.','Enim Non PC','04/05/17','libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam','Culture','Moderated',49);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna.','A Scelerisque Sed Limited','04/05/17','luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat','Culture','Moderated',3);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Isabella','Nulla Integer Corporation','04/05/17','id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet','Culture','Moderated',14);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Donec consectetuer mauris id sapien.','Ac Mattis Semper Industries','04/05/17','egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula.','Culture','Moderated',48);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. ','Eu Company','04/05/17','massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non','Culture','Moderated',6);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','Malesuada Vel Consulting','04/05/17','sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu','Culture','Moderated',4);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Nam ac nulla, in tincidunt congue turpis, in condimentum.','At Arcu LLC','04/05/17','Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales','Science','Visible',34);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Morbi quis urna, nunc quis arcu vel quam dignissim pharetra.','Scelerisque Lorem Ipsum Institute','04/05/17','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam','Sports','Moderated',1);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Mauris magna, duis dignissim tempor arcu.','Sapien Industries','04/05/17','Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,','World','Visible',16);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Lorem fringilla ornare placerat, orci lacus vestibulum lorem.','Molestie Associates','04/05/17','lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,','Culture','Moderated',48);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Pellentesque ultricies dignissim lacus, aliquam rutrum lorem ac risus.','Placerat Velit Corporation','04/05/17','vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed','World','Visible',7);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.','Mollis Vitae LLP','04/05/17','Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.','World','Visible',31);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Suspendisse tristique neque venenatis lacus.','Fermentum Convallis Corp.','04/05/17','eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris','World','Visible',20);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Aenean egestas hendrerit neque, n ornare sagittis felis.','Elementum At LLC','04/05/17','aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes,','World','Visible',44);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Mauris blandit enim consequat purus, maecenas libero est, congue a.','Aptent Company','04/05/17','eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi','Politics','Visible',41);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Nunc sed orci lobortis augue scelerisque mollis, phasellus libero mauris.','Semper Auctor Mauris Associates','04/05/17','Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a,','Politics','Visible',13);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Quisque ac libero nec ligula consectetuer rhoncus, nullam velit dui.','Senectus Et Limited','04/05/17','arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis,','Politics','Visible',33);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Proin sed turpis nec mauris blandit mattis.','Ipsum Incorporated','04/05/17','nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent','Politics','Visible',36);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Pellentesque tincidunt tempus risus, donec egestas.','Dui Industries','04/05/17','vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper','Politics','Visible',43);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Tellus sem mollis dui, in sodales elit erat vitae risus.','Aliquam Vulputate Corp.','04/05/17','tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis','Politics','Visible',3);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Phasellus in felis, nulla tempor augue ac ipsum, phasellus vitae mauris sit amet.','Lacus Mauris LLC','04/05/17','Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam','Culture','Visible',11);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est.','Enim Non PC','04/05/17','libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam','Culture','Visible',47);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna.','A Scelerisque Sed Limited','04/05/17','luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat','Culture','Visible',4);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Isabella','Nulla Integer Corporation','04/05/17','id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet','Culture','Visible',17);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Donec consectetuer mauris id sapien.','Ac Mattis Semper Industries','04/05/17','egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula.','Culture','Visible',41);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. ','Eu Company','04/05/17','massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non','Culture','Visible',5);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','Malesuada Vel Consulting','04/05/17','sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu','Science','Visible',4);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Nam ac nulla, in tincidunt congue turpis, in condimentum.','At Arcu LLC','04/05/17','Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales','Science','Visible',35);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Morbi quis urna, nunc quis arcu vel quam dignissim pharetra.','Scelerisque Lorem Ipsum Institute','04/05/17','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam','Science','Visible',1);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Mauris magna, duis dignissim tempor arcu.','Sapien Industries','04/05/17','Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,','Science','Visible',16);
INSERT INTO article (abstract,title,date,content,category,visibility,idUser) VALUES ('Lorem fringilla ornare placerat, orci lacus vestibulum lorem.','Molestie Associates','04/05/17','lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,','Science','Visible',48);





INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('risus a ultricies adipiscing, enim mi tempor lorem, eget','04/05/17',2,'Visible',19);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec','04/05/17',10,'Visible',38);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('tincidunt, nunc ac mattis ornare, lectus ante dictum','04/05/17',7,'Visible',23);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('mauris ut mi. Duis','04/05/17',24,'Visible',35);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('libero est, congue a, aliquet','04/05/17',1,'Visible',24);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('ullamcorper eu, euismod ac, fermentum','04/05/17',9,'Visible',36);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('neque non quam.','04/05/17',20,'Visible',47);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('libero. Proin mi.','04/05/17',2,'Visible',43);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('Aliquam gravida mauris ut mi. Duis risus odio, auctor','04/05/17',18,'Visible',9);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('ullamcorper, nisl arcu iaculis enim,','04/05/17',6,'Visible',2);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('mauris, rhoncus','04/05/17',1,'Visible',41);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum','04/05/17',6,'Visible',31);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum','04/05/17',18,'Visible',43);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim','04/05/17',1,'Visible',32);
INSERT INTO comment (text,date,idArticle,visibility,idUser) VALUES ('pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum.','04/05/17',1,'Visible',48);

INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('amet','04/05/17',12,'Visible',4);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('quis diam. Pellentesque habitant morbi tristique senectus et netus et','04/05/17',8,'Visible',39);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('ut, pellentesque eget, dictum','04/05/17',13,'Visible',15);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae,','04/05/17',8,'Visible',21);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('mauris eu elit. Nulla facilisi. Sed neque. Sed','04/05/17',8,'Visible',30);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('dolor sit','04/05/17',10,'Visible',30);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('Proin','04/05/17',11,'Visible',11);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('blandit','04/05/17',7,'Visible',40);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('erat. Etiam vestibulum massa rutrum magna. Cras','04/05/17',6,'Visible',23);
INSERT INTO comment (text,date,idReply,visibility,idUser) VALUES ('libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus','04/05/17',15,'Visible',38);



INSERT INTO follower (idFollowed,idFollower) VALUES (25,14);
INSERT INTO follower (idFollowed,idFollower) VALUES (20,16);
INSERT INTO follower (idFollowed,idFollower) VALUES (15,30);
INSERT INTO follower (idFollowed,idFollower) VALUES (25,3);
INSERT INTO follower (idFollowed,idFollower) VALUES (4,5);
INSERT INTO follower (idFollowed,idFollower) VALUES (19,14);
INSERT INTO follower (idFollowed,idFollower) VALUES (10,19);
INSERT INTO follower (idFollowed,idFollower) VALUES (14,1);
INSERT INTO follower (idFollowed,idFollower) VALUES (25,22);
INSERT INTO follower (idFollowed,idFollower) VALUES (24,6);
INSERT INTO follower (idFollowed,idFollower) VALUES (10,8);
INSERT INTO follower (idFollowed,idFollower) VALUES (28,13);
INSERT INTO follower (idFollowed,idFollower) VALUES (5,12);
INSERT INTO follower (idFollowed,idFollower) VALUES (21,7);
INSERT INTO follower (idFollowed,idFollower) VALUES (11,3);
INSERT INTO follower (idFollowed,idFollower) VALUES (27,7);
INSERT INTO follower (idFollowed,idFollower) VALUES (9,2);
INSERT INTO follower (idFollowed,idFollower) VALUES (10,18);
INSERT INTO follower (idFollowed,idFollower) VALUES (27,17);
INSERT INTO follower (idFollowed,idFollower) VALUES (25,26);
INSERT INTO follower (idFollowed,idFollower) VALUES (24,22);
INSERT INTO follower (idFollowed,idFollower) VALUES (11,30);
INSERT INTO follower (idFollowed,idFollower) VALUES (20,1);
INSERT INTO follower (idFollowed,idFollower) VALUES (14,6);
INSERT INTO follower (idFollowed,idFollower) VALUES (13,9);
INSERT INTO follower (idFollowed,idFollower) VALUES (27,28);
INSERT INTO follower (idFollowed,idFollower) VALUES (21,23);
INSERT INTO follower (idFollowed,idFollower) VALUES (8,2);
INSERT INTO follower (idFollowed,idFollower) VALUES (12,30);
INSERT INTO follower (idFollowed,idFollower) VALUES (4,22);


INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',1);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',2);
INSERT INTO image (description,url,idArticle) VALUES ('vel','garden.png',3);
INSERT INTO image (description,url,idArticle) VALUES ('luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi','lawyer.png',4);
INSERT INTO image (description,url,idArticle) VALUES ('in faucibus orci luctus et ultrices','books.png',5);
INSERT INTO image (description,url,idArticle) VALUES ('nonummy. Fusce fermentum fermentum arcu.','city.png',6);
INSERT INTO image (description,url,idArticle) VALUES ('lacus.','garden.png',7);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',8);
INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',9);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',10);
INSERT INTO image (description,url,idArticle) VALUES ('vel','garden.png',11);
INSERT INTO image (description,url,idArticle) VALUES ('luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi','lawyer.png',12);
INSERT INTO image (description,url,idArticle) VALUES ('in faucibus orci luctus et ultrices','books.png',13);
INSERT INTO image (description,url,idArticle) VALUES ('nonummy. Fusce fermentum fermentum arcu.','city.png',14);
INSERT INTO image (description,url,idArticle) VALUES ('lacus.','garden.png',15);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',16);
INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',17);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',32);
INSERT INTO image (description,url,idArticle) VALUES ('vel','garden.png',18);
INSERT INTO image (description,url,idArticle) VALUES ('luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi','lawyer.png',19);
INSERT INTO image (description,url,idArticle) VALUES ('in faucibus orci luctus et ultrices','books.png',20);
INSERT INTO image (description,url,idArticle) VALUES ('nonummy. Fusce fermentum fermentum arcu.','city.png',21);
INSERT INTO image (description,url,idArticle) VALUES ('lacus.','garden.png',22);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',23);
INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',24);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',25);
INSERT INTO image (description,url,idArticle) VALUES ('vel','garden.png',26);
INSERT INTO image (description,url,idArticle) VALUES ('luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi','lawyer.png',27);
INSERT INTO image (description,url,idArticle) VALUES ('in faucibus orci luctus et ultrices','books.png',28);
INSERT INTO image (description,url,idArticle) VALUES ('nonummy. Fusce fermentum fermentum arcu.','city.png',29);
INSERT INTO image (description,url,idArticle) VALUES ('lacus.','garden.png',30);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',31);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',33);
INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',34);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',35);
INSERT INTO image (description,url,idArticle) VALUES ('vel','garden.png',36);
INSERT INTO image (description,url,idArticle) VALUES ('luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi','lawyer.png',37);
INSERT INTO image (description,url,idArticle) VALUES ('in faucibus orci luctus et ultrices','books.png',38);
INSERT INTO image (description,url,idArticle) VALUES ('nonummy. Fusce fermentum fermentum arcu.','city.png',39);
INSERT INTO image (description,url,idArticle) VALUES ('lacus.','garden.png',40);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',41);
INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',42);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',43);
INSERT INTO image (description,url,idArticle) VALUES ('vel','garden.png',44);
INSERT INTO image (description,url,idArticle) VALUES ('luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi','lawyer.png',45);
INSERT INTO image (description,url,idArticle) VALUES ('in faucibus orci luctus et ultrices','books.png',46);
INSERT INTO image (description,url,idArticle) VALUES ('nonummy. Fusce fermentum fermentum arcu.','city.png',47);
INSERT INTO image (description,url,idArticle) VALUES ('lacus.','garden.png',48);
INSERT INTO image (description,url,idArticle) VALUES ('Vestibulum','lawyer.png',49);
INSERT INTO image (description,url,idArticle) VALUES ('diam vel arcu. Curabitur ut odio vel est tempor bibendum.','books.png',50);
INSERT INTO image (description,url,idArticle) VALUES ('lorem lorem, luctus ut, pellentesque eget,','city.png',51);



INSERT INTO tags (tag) VALUES ('Samuel');
INSERT INTO tags (tag) VALUES ('Lesley');
INSERT INTO tags (tag) VALUES ('Stone');
INSERT INTO tags (tag) VALUES ('Flynn');
INSERT INTO tags (tag) VALUES ('Molly');
INSERT INTO tags (tag) VALUES ('Winter');
INSERT INTO tags (tag) VALUES ('Risa');
INSERT INTO tags (tag) VALUES ('Dieter');
INSERT INTO tags (tag) VALUES ('Dominic');
INSERT INTO tags (tag) VALUES ('Shana');
INSERT INTO tags (tag) VALUES ('Kyra');
INSERT INTO tags (tag) VALUES ('Fulton');
INSERT INTO tags (tag) VALUES ('Kiayada');
INSERT INTO tags (tag) VALUES ('Uriel');
INSERT INTO tags (tag) VALUES ('Hilary');


INSERT INTO linktag (idTag,idArticle) VALUES (5,2);
INSERT INTO linktag (idTag,idArticle) VALUES (13,15);
INSERT INTO linktag (idTag,idArticle) VALUES (9,26);
INSERT INTO linktag (idTag,idArticle) VALUES (5,22);
INSERT INTO linktag (idTag,idArticle) VALUES (8,8);
INSERT INTO linktag (idTag,idArticle) VALUES (14,9);
INSERT INTO linktag (idTag,idArticle) VALUES (6,29);
INSERT INTO linktag (idTag,idArticle) VALUES (13,9);
INSERT INTO linktag (idTag,idArticle) VALUES (7,10);
INSERT INTO linktag (idTag,idArticle) VALUES (8,22);
INSERT INTO linktag (idTag,idArticle) VALUES (13,4);
INSERT INTO linktag (idTag,idArticle) VALUES (8,21);
INSERT INTO linktag (idTag,idArticle) VALUES (8,18);
INSERT INTO linktag (idTag,idArticle) VALUES (6,1);
INSERT INTO linktag (idTag,idArticle) VALUES (15,9);
INSERT INTO linktag (idTag,idArticle) VALUES (14,30);
INSERT INTO linktag (idTag,idArticle) VALUES (11,14);
INSERT INTO linktag (idTag,idArticle) VALUES (8,25);
INSERT INTO linktag (idTag,idArticle) VALUES (5,23);
INSERT INTO linktag (idTag,idArticle) VALUES (15,27);
INSERT INTO linktag (idTag,idArticle) VALUES (6,20);
INSERT INTO linktag (idTag,idArticle) VALUES (5,15);
INSERT INTO linktag (idTag,idArticle) VALUES (5,3);
INSERT INTO linktag (idTag,idArticle) VALUES (12,27);
INSERT INTO linktag (idTag,idArticle) VALUES (8,19);
INSERT INTO linktag (idTag,idArticle) VALUES (13,28);
INSERT INTO linktag (idTag,idArticle) VALUES (3,30);
INSERT INTO linktag (idTag,idArticle) VALUES (15,17);
INSERT INTO linktag (idTag,idArticle) VALUES (11,24);




INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',5,21);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',25,32);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',2,43);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',3,9);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',5,48);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',2,39);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',26,48);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',24,19);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',9,34);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',5,4);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',2,33);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',21,29);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',1,25);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',19,3);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',15,43);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',23,23);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',22,34);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',22,32);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',12,17);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',11,40);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',16,31);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',18,19);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',17,25);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',20,50);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',13,34);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',22,4);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',6,11);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',29,21);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (1,'04/05/17',22,46);
INSERT INTO rating (value,date,idArticle,idUser) VALUES (-1,'04/05/17',15,34);

INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',4,26);
INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',23,4);
INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',11,12);
INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',6,23);
INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',8,38);
INSERT INTO rating (value,date,idComment,idUser) VALUES (-1,'04/05/17',5,30);
INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',4,38);
INSERT INTO rating (value,date,idComment,idUser) VALUES (-1,'04/05/17',18,4);
INSERT INTO rating (value,date,idComment,idUser) VALUES (1,'04/05/17',19,48);
INSERT INTO rating (value,date,idComment,idUser) VALUES (-1,'04/05/17',23,26);




INSERT INTO report (description,state,idArticle,idUser) VALUES ('facilisi. Sed neque. Sed eget','Pending',22,37);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('morbi tristique senectus et netus','Pending',29,37);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh','Accepted',23,5);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('Ut tincidunt orci','Accepted',28,48);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('magna.','Ignored',12,29);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('hendrerit id, ante. Nunc','Ignored',12,22);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('quam. Pellentesque habitant','Pending',7,5);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus.','Pending',28,39);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam','Accepted',29,40);
INSERT INTO report (description,state,idArticle,idUser) VALUES ('consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque,','Accepted',29,41);

INSERT INTO report (description,state,idComment,idUser) VALUES ('enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis','Pending',7,39);
INSERT INTO report (description,state,idComment,idUser) VALUES ('ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu,','Pending',3,27);
INSERT INTO report (description,state,idComment,idUser) VALUES ('sagittis semper. Nam tempor diam dictum','Accepted',5,22);
INSERT INTO report (description,state,idComment,idUser) VALUES ('Nullam nisl. Maecenas malesuada fringilla est.','Accepted',13,11);
INSERT INTO report (description,state,idComment,idUser) VALUES ('lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod','Ignored',22,36);




INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',27,45,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',24,35,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',10,17,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',8,39,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',23,16,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',15,28,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',4,11,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',19,40,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',13,35,true);
INSERT INTO notification (date,idArticle,idUser,read) VALUES ('04/05/17',28,35,true);

INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',3,26,true);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',4,27,true);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',21,49,true);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',20,41,false);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',13,49,false);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',16,48,true);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',23,47,true);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',4,18,false);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',5,43,true);
INSERT INTO notification (date,idComment,idUser,read) VALUES ('04/05/17',24,2,false);



INSERT INTO suspension (idUser,start,terminate,reason,ban) VALUES (17,'04/05/17', '11/05/17','Lorem ipsum dolor sit amet, consectetuer adipiscing','Soft');
INSERT INTO suspension (idUser,start,terminate,reason,ban) VALUES (15,'04/05/17','11/05/17','Lorem ipsum dolor sit amet, consectetuer','Soft');
INSERT INTO suspension (idUser,start,terminate,reason,ban) VALUES (16,'04/05/17','08/05/17','Lorem ipsum dolor','Soft');
INSERT INTO suspension (idUser,start,terminate,reason,ban) VALUES (7,'04/05/17','12/20/17','Lorem ipsum dolor sit amet,','Hard');
